### ISSUE TITLE
AES-256 Example

### ISSUE THREAD

**Issue by onury** [luke-park/SecureCompatibleEncryptionExamples#12]
_I use this mainly for Node.js._

I understand that AES with a 128-bit key was chosen due to the Java Unlimited Strength Policy that requires key sizes of no more than 128-bits due to cryptography export laws. 

You said this can be trivially changed to 256-bit AES by changing the `ALGORITHM_KEY_SIZE` (and in some cases, `ALGORITHM_NAME`) parameter.

Could you provide a configuration for this that would work across platforms & languages. For example, would you say below would be performant and work across platforms:

```js
const ALGORITHM_NAME = "aes-256-cbc";
const ALGORITHM_NONCE_SIZE = 12;
const ALGORITHM_TAG_SIZE = 16;
const ALGORITHM_KEY_SIZE = 32;
const PBKDF2_NAME = "sha256";
const PBKDF2_SALT_SIZE = 16;
const PBKDF2_ITERATIONS = 32767;
```

_Note: [This link](https://golb.hplar.ch/2017/10/JCE-policy-changes-in-Java-SE-8u151-and-8u152.html) (Oracle Java 8u162) indicates that Java cryptography is no longer restricted._

**Comment by luke-park** [comment]
Yes - the configuration you provide is fine and will work across platforms - obviously with the assumption that you actually do provide a 256-bit key (or use the `encrypt_string` methods).

**Comment by onury** [comment]
When I use `aes-256-cbc`,
`cipher.getAuthTag()` below complains that it expects a gcm algorithm.

```js
// encrypt method
return Buffer.concat([nonce, ciphertext, cipher.getAuthTag()]);
```
So, instead I'm configuring `aes-256-gcm`.

**Comment by onury** [comment]
Thanks.

**Comment by luke-park** [comment]
Sorry - didn't notice you had `cbc` - all of these examples will only work with the `gcm` mode of operation - suggest you keep it this way - there are few reasons to use CBC these days.
