### ISSUE TITLE
Need help to convert java decrypt code to node JS code

### ISSUE THREAD

**Issue by HariHaraThambudu** [luke-park/SecureCompatibleEncryptionExamples#7]
@luke-park  the below code is not an issue.can you please help to convert the below java code.  
Followed your answer  as like from stackoverflow
https://stackoverflow.com/questions/49021171/how-to-derive-iv-and-key-to-crypto-createcipheriv-for-decryption

          //Private Variables
            private Secretkeyfactory secretkeyfactory ;
            private Cipher cipher;

            //Constructor
            public Decrypt128CBC()
            {
              this.secretkeyfactory =Secretkeyfactory.getInstance("PBKDF2WithHmacSHA1");
              this.cipher=Cipher.getInstance("AES/CBC/PKCS5Padding")
            }
                Public string DecryptedValue(String Ecryptedbase64string,String secKey)
                {
                 byte[] dcdbytes=Base64.decodeBase64(Ecryptedbase64string.getBytes());
                byte[] calculatesalt=Arrays.copyOfRange(dcdbytes,0,32);
                byte[] initialvecto=Arrays.copyOfRange(dcdbytes,32,48);
                byte[] encodedtext=Arrays.copyOfRange(dcdbytes,48,dcdbytes.length);
                SecretKey sk=getRandompwd(calculatesalt,secKey);
                IvParameterSpec vectspec=new IvParameterSpec(initialvecto);
                byte[] decrtptxt=null;
                synchronized(cipher){
                cipher.init(Cipher.DECRYPT_MODE,sk,vectspec);
                decrtptxt=cipher.doFinal(encodedtext)
                }
            String finalvalue=new String(decrtptxt);
            return finalvalue;
                }
            
            private SecretKey getRandompwd(byte[] salt,String secKey)
            {
            SecretKeySpec objSecKeySpec=new SecretKeySpec(Base64.decodeBase64(secKey),"HmacSHA1");    
            String skey=Base64.encodeBase64String(objSecKeySpec.getEncoded());
            KeySpec kspec=new PBEKeySpec(skey.toCharArray(),salt,76456,128);
            SecretKey tmpSecKey=secretKeyKactory.generateSecret(kspec);
            byte[] encoded=tmpSecKey.getEncoded();
            return new SecretKeySpec(encoded,'AES')
            }

Here is the node JS code I tried. I tried lots of option with crypto but not able to. My final output is coming with some junk characters like square,symbols etc...

    var crypto=require('crypto');

    var Ecryptedbase64string='fsffsfgf6575FGHDM767fsffsfs...…...';
    var DecryptKey='J8nMD7ZnFg......';

    var byteEncryptedString=new Buffer(Ecryptedbase64string,'base64');
    var binaryKey=new Buffer(DecryptKey,""base64);
    var salt=byteEncryptedString.slice(0,32);
    var iv=byteEncryptedString.slice(32,48);
    var cipherText=byteEncryptedString.slice(48,byteEncryptedString.length);
   

    var callback=function(err,key){
    let cipher=crypto.createDecipheriv('AES-128-CBC',key,iv);
    let finalDecrptedText=Buffer.concat([cipher.update(cipherText),cipher.final()]);
    };

    crypto.pbkdf2(binaryKey,salt,76456,16,callback);

**Comment by luke-park** [comment]
I'm closing this issue as it has literally nothing to do with this repository - you've already asked a question on StackOverflow, wait for your answer there.

**Comment by HariHaraThambudu** [comment]
Sure. Thanks
